sudo: false
script: bundle exec rake
before_script: ${PHANTOMJS:-phantomjs} --version
before_install:
   - mkdir -p travis-phantomjs21
   - if [ ! -f $PWD/travis-phantomjs21/phantomjs ]; then wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/phantomjs-2.1-linux-x86_64.tar.bz2; tar -xvf $PWD/phantomjs-2.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs21 --strip-components 2 phantomjs-2.1.1-linux-x86_64/bin/phantomjs; fi
   - chmod +x $PWD/travis-phantomjs21/phantomjs
cache:
  directories:
    - $PWD/travis-phantomjs21

rvm:
  - 2.3.0
  - 2.2.2
  - 2.1.6
  - 2.0.0
  - rbx
gemfile:
  - Gemfile
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - PHANTOMJS=$PWD/travis-phantomjs21/phantomjs

matrix:
  include:
    - rvm: 2.3.1
      gemfile: gemfiles/Gemfile.capybara_master
  allow_failures:
    - gemfile: gemfiles/Gemfile.capybara_master
